; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.13 on Fri Sep 16 2022 22:17:44 GMT+0200 (Central European Summer Time)

